# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable all dependabot updates, except when we explicitly ask for them.
    # This does not disable security updates: those have a hardcoded limit of
    # 10 which is separate from this limit.
    open-pull-requests-limit: 0
