#!/usr/bin/python3 -sS


import io
import sys

fifo_path_from_user, fifo_path_to_user = sys.argv[1:]

# The order these are opened is very important.  It must match the stub.
fifo_to_user = io.open(fifo_path_to_user, "wb", buffering=0)
fifo_from_user = io.open(fifo_path_from_user, "rb", buffering=0)

input_value = int(io.open("input.txt", "rb").readline())

correct = True

# Speak the to program a few times, check what it does, and output the last
# line.
for i in list(range(10, 20)) + [0]:
    x = i + input_value
    # Write a question to the candidate executable.
    fifo_to_user.write(b"%d\n" % x)
    # Read their response.
    l = fifo_from_user.readline()
    # EOF?
    if l == b'':
        correct = False
        break
    # These are the only things we expect from our stub.
    if l.strip() != b'correct %d' % x:
        correct = False
        break

    correct = correct and (int(l.split()[1]) == x)
else:
    # Tell stub to exit.
    fifo_to_user.write(b"0\n")

# This file exists just for convenience.
io.open("output.txt", "wb").write(l + b"\n")

# This is the final score.
if correct:
    print("1")
else:
    print("0")
