#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# Contest Management System - http://cms-dev.github.io/
# Copyright © 2013 Luca Wehrstedt <luca.wehrstedt@gmail.com>
# Copyright © 2016 Stefano Maggiolo <s.maggiolo@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

# We enable monkey patching to make many libraries gevent-friendly
# (for instance, urllib3, used by requests)
import gevent.monkey
gevent.monkey.patch_all()

import argparse
import logging
import sys

from cms import ConfigError, contest_id_from_args, get_safe_shard
from cms.db import ask_for_contest, test_db_connection
from cms.server.contest import ContestWebServer


logger = logging.getLogger(__name__)


def main():
    """Parse arguments and launch service.

    """
    parser = argparse.ArgumentParser(
        description="Contestants' web server for CMS.")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-c", "--contest-id", action="store", type=int,
                       help="id of the contest to automatically load")
    group.add_argument("-a", "--all-contests", action="store_true",
                       help="allow contestants to access all contests")
    parser.add_argument("shard", action="store", type=int, nargs="?")
    args = parser.parse_args()

    try:
        args.shard = get_safe_shard("ContestWebServer", args.shard)
    except ValueError:
        raise ConfigError("Couldn't autodetect shard number and "
                          "no shard specified for service %s, "
                          "quitting." % ("ContestWebServer", ))

    test_db_connection()

    if args.all_contests:
        success = ContestWebServer(args.shard).run()
    else:
        success = ContestWebServer(
            args.shard,
            contest_id_from_args(args.contest_id, ask_for_contest)).run()

    return 0 if success is True else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ConfigError as error:
        logger.critical(error.message)
        sys.exit(1)
