#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# Contest Management System - http://cms-dev.github.io/
# Copyright © 2013 Luca Wehrstedt <luca.wehrstedt@gmail.com>
# Copyright © 2016 Stefano Maggiolo <s.maggiolo@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

# We enable monkey patching to make many libraries gevent-friendly
# (for instance, urllib3, used by requests)
import gevent.monkey
gevent.monkey.patch_all()

import argparse
import logging
import sys

from cms import ConfigError, contest_id_from_args, get_safe_shard
from cms.db import ask_for_contest, test_db_connection
from cms.service.ResourceService import ResourceService


logger = logging.getLogger(__name__)


def main():
    """Parses arguments and launch service.

    """
    parser = argparse.ArgumentParser(
        description="Resource monitor and service starter for CMS.")
    parser.add_argument("-a", "--autorestart", action="store", type=int,
                        nargs="?", const=-1, metavar="CONTEST_ID",
                        help="restart automatically services on its machine")
    parser.add_argument("shard", action="store", type=int, nargs="?")
    args = parser.parse_args()

    try:
        args.shard = get_safe_shard("ResourceService", args.shard)
    except ValueError:
        raise ConfigError("Couldn't autodetect shard number and "
                          "no shard specified for service %s, "
                          "quitting." % ("ResourceService", ))

    test_db_connection()

    if args.autorestart is not None:
        if args.autorestart == -1:
            success = ResourceService(
                args.shard, contest_id=ask_for_contest()).run()
        else:
            success = ResourceService(
                args.shard,
                contest_id=contest_id_from_args(
                    args.autorestart, ask_for_contest)).run()
    else:
        success = ResourceService(args.shard).run()
    return 0 if success is True else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ConfigError as error:
        logger.critical(error.message)
        sys.exit(1)
